// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: primes/v1/primes.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PrimeRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PrimeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PrimeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PrimeRequestMultiError, or
// nil if none found.
func (m *PrimeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PrimeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetMin() < 2 {
		err := PrimeRequestValidationError{
			field:  "Min",
			reason: "value must be greater than or equal to 2",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetMax() > 9999999999 {
		err := PrimeRequestValidationError{
			field:  "Max",
			reason: "value must be less than or equal to 9999999999",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PrimeRequestMultiError(errors)
	}

	return nil
}

// PrimeRequestMultiError is an error wrapping multiple validation errors
// returned by PrimeRequest.ValidateAll() if the designated constraints aren't met.
type PrimeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PrimeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PrimeRequestMultiError) AllErrors() []error { return m }

// PrimeRequestValidationError is the validation error returned by
// PrimeRequest.Validate if the designated constraints aren't met.
type PrimeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrimeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrimeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrimeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrimeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrimeRequestValidationError) ErrorName() string { return "PrimeRequestValidationError" }

// Error satisfies the builtin error interface
func (e PrimeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrimeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrimeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrimeRequestValidationError{}

// Validate checks the field values on PrimeResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PrimeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PrimeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PrimeResponseMultiError, or
// nil if none found.
func (m *PrimeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PrimeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Prime

	if len(errors) > 0 {
		return PrimeResponseMultiError(errors)
	}

	return nil
}

// PrimeResponseMultiError is an error wrapping multiple validation errors
// returned by PrimeResponse.ValidateAll() if the designated constraints
// aren't met.
type PrimeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PrimeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PrimeResponseMultiError) AllErrors() []error { return m }

// PrimeResponseValidationError is the validation error returned by
// PrimeResponse.Validate if the designated constraints aren't met.
type PrimeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrimeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrimeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrimeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrimeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrimeResponseValidationError) ErrorName() string { return "PrimeResponseValidationError" }

// Error satisfies the builtin error interface
func (e PrimeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrimeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrimeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrimeResponseValidationError{}
