// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: primes/v1/primes.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Primes_Get_FullMethodName = "/primes.v1.Primes/Get"
)

// PrimesClient is the client API for Primes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimesClient interface {
	Get(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (*PrimeResponse, error)
}

type primesClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimesClient(cc grpc.ClientConnInterface) PrimesClient {
	return &primesClient{cc}
}

func (c *primesClient) Get(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (*PrimeResponse, error) {
	out := new(PrimeResponse)
	err := c.cc.Invoke(ctx, Primes_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimesServer is the server API for Primes service.
// All implementations must embed UnimplementedPrimesServer
// for forward compatibility
type PrimesServer interface {
	Get(context.Context, *PrimeRequest) (*PrimeResponse, error)
	mustEmbedUnimplementedPrimesServer()
}

// UnimplementedPrimesServer must be embedded to have forward compatible implementations.
type UnimplementedPrimesServer struct {
}

func (UnimplementedPrimesServer) Get(context.Context, *PrimeRequest) (*PrimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPrimesServer) mustEmbedUnimplementedPrimesServer() {}

// UnsafePrimesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimesServer will
// result in compilation errors.
type UnsafePrimesServer interface {
	mustEmbedUnimplementedPrimesServer()
}

func RegisterPrimesServer(s grpc.ServiceRegistrar, srv PrimesServer) {
	s.RegisterService(&Primes_ServiceDesc, srv)
}

func _Primes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Primes_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimesServer).Get(ctx, req.(*PrimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Primes_ServiceDesc is the grpc.ServiceDesc for Primes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Primes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primes.v1.Primes",
	HandlerType: (*PrimesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Primes_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "primes/v1/primes.proto",
}
