global:
  scrape_interval:     1s
  evaluation_interval: 1s
  external_labels:
    cluster: primes
    namespace: primes

scrape_configs:
  - job_name: 'primes'
    scrape_interval: 500ms
    # scheme: https
    static_configs:
      - targets: ['localhost:8080']